/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ui: {
          root: 'var(--ui-bg-root)',
          panel: 'var(--ui-bg-panel)',
          header: 'var(--ui-bg-header)',
          surface: 'var(--ui-bg-surface)',
          input: 'var(--ui-bg-input)',
          hover: 'var(--ui-bg-hover)',
          active: 'var(--ui-bg-active)',
          border: 'var(--ui-border-default)',
          borderSubtle: 'var(--ui-border-subtle)',
          borderDefault: 'var(--ui-border-default)',
          borderStrong: 'var(--ui-border-strong)',
          borderFocus: 'var(--ui-border-focus)',
          'border-subtle': 'var(--ui-border-subtle)',
          'border-default': 'var(--ui-border-default)',
          'border-strong': 'var(--ui-border-strong)',
          'border-focus': 'var(--ui-border-focus)',
          accent: 'var(--ui-accent)',
          accentHover: 'var(--ui-accent-hover)',
          accentSubtle: 'var(--ui-accent-subtle)',
          'accent-hover': 'var(--ui-accent-hover)',
          'accent-subtle': 'var(--ui-accent-subtle)',
          onAccent: 'var(--ui-on-accent)',
          'on-accent': 'var(--ui-on-accent)',
          textPrimary: 'var(--ui-text-primary)',
          textSecondary: 'var(--ui-text-secondary)',
          textMuted: 'var(--ui-text-muted)',
          textAccent: 'var(--ui-text-accent)',
          'text-primary': 'var(--ui-text-primary)',
          'text-secondary': 'var(--ui-text-secondary)',
          'text-muted': 'var(--ui-text-muted)',
          'text-accent': 'var(--ui-text-accent)',
        },
        dcc: {
          900: '#121316',
          850: '#181a1f',
          800: '#202228',
          750: '#282b33',
          700: '#323640',
          600: '#434855',
          500: '#646b7d',
          accent: '#6366f1',
          accentHover: '#4f46e5',
          retroYellow: '#f59e0b',
          retroGreen: '#10b981',
          retroCyan: '#06b6d4',
          retroMagenta: '#ec4899',
        }
      },
      borderColor: {
        DEFAULT: 'var(--ui-border-default)',
      },
      borderRadius: {
        'xs': '2px',
        'sm': '3px',
        'md': '4px',
      },
      height: {
        'ui-header': 'var(--ui-h-header)',
        'ui-toolbar': 'var(--ui-h-toolbar)',
        'ui-control': 'var(--ui-h-control)',
        'ui-control-sm': 'var(--ui-h-control-sm)',
      },
      fontFamily: {
        mono: ['"JetBrains Mono"', 'Consolas', 'monospace'],
        pixel: ['"Press Start 2P"', 'monospace', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
